// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./Home.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "../node_modules/@rescript/react/src/RescriptReactRouter.js";

function App(props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (match && match.hd === "~jhlee" && !match.tl) {
    return JsxRuntime.jsx(Home.make, {});
  } else {
    return "404";
  }
}

var make = App;

export {
  make ,
}
/* Home Not a pure module */
