// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Home(props) {
  return JsxRuntime.jsxs("article", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Jaeho Lee"
                    }),
                JsxRuntime.jsxs("ul", {
                      children: [
                        JsxRuntime.jsx("li", {
                              children: JsxRuntime.jsx("a", {
                                    children: "GitHub profile",
                                    href: "https://github.com/Zeta611"
                                  })
                            }),
                        JsxRuntime.jsx("li", {
                              children: JsxRuntime.jsx("a", {
                                    children: "Curriculum Vitae",
                                    href: "https://nbviewer.org/github/Zeta611/curriculum-vitae/blob/main/build/default/default.pdf"
                                  })
                            }),
                        JsxRuntime.jsx("li", {
                              children: JsxRuntime.jsx("a", {
                                    children: "Personal blog",
                                    href: "https://zetablog.io"
                                  })
                            })
                      ]
                    }),
                JsxRuntime.jsx("img", {
                      className: "w-[270px] h-[360px]",
                      alt: "Photo of Jaeho Lee",
                      src: "./jhlee_photo.jpg"
                    }),
                JsxRuntime.jsx("h2", {
                      children: "Research Interests"
                    }),
                JsxRuntime.jsxs("ul", {
                      children: [
                        JsxRuntime.jsx("li", {
                              children: "Programming Languages"
                            }),
                        JsxRuntime.jsx("li", {
                              children: "Functional Programming"
                            }),
                        JsxRuntime.jsx("li", {
                              children: "Software Engineering"
                            }),
                        JsxRuntime.jsx("li", {
                              children: "Static Analysis"
                            })
                      ]
                    }),
                JsxRuntime.jsx("h2", {
                      children: "Projects"
                    }),
                JsxRuntime.jsxs("ul", {
                      children: [
                        JsxRuntime.jsx("li", {
                              children: JsxRuntime.jsx("a", {
                                    children: "React-tRace: Formal semantics and static analysis of React hooks",
                                    href: "https://github.com/React-Analysis/react-trace"
                                  })
                            }),
                        JsxRuntime.jsx("li", {
                              children: JsxRuntime.jsx("a", {
                                    children: "easyword.kr: A platform for translating CS jargons into easy to understand Korean",
                                    href: "https://easyword.kr"
                                  })
                            }),
                        JsxRuntime.jsx("li", {
                              children: JsxRuntime.jsx("a", {
                                    children: "simplebnf: an intuitive BNF grammar typesetting using DSL",
                                    href: "https://github.com/Zeta611/simplebnf"
                                  })
                            }),
                        JsxRuntime.jsx("li", {
                              children: JsxRuntime.jsx("a", {
                                    children: "STAPPL: a statically-typed probabilistic programming language",
                                    href: "https://github.com/Zeta611/stappl"
                                  })
                            }),
                        JsxRuntime.jsx("li", {
                              children: JsxRuntime.jsx("a", {
                                    children: "prospect-analyzer: a shape-checker for programs with holes",
                                    href: "https://github.com/Zeta611/prospect-analyzer"
                                  })
                            }),
                        JsxRuntime.jsx("li", {
                              children: JsxRuntime.jsx("a", {
                                    children: "Rust MIR Escape Analysis: An Application to Protecting Dynamic Pointer Metadata",
                                    href: "https://github.com/Zeta611/rust-escape-analysis-thesis"
                                  })
                            })
                      ]
                    }),
                JsxRuntime.jsx("h2", {
                      children: "Education"
                    }),
                JsxRuntime.jsxs("ul", {
                      children: [
                        JsxRuntime.jsx("li", {
                              children: "MS, Computer Science and Engineering, Seoul National University (Mar 2024 – )"
                            }),
                        JsxRuntime.jsxs("ul", {
                              children: [
                                JsxRuntime.jsx("li", {
                                      children: "ROPAS (Mar 2024 – )"
                                    }),
                                JsxRuntime.jsx("li", {
                                      children: "GPA 4.15/4.3"
                                    })
                              ]
                            }),
                        JsxRuntime.jsx("li", {
                              children: "BS, Electrical and Computer Engineering, Seoul National University (Mar 2018 – Feb 2024)"
                            }),
                        JsxRuntime.jsxs("ul", {
                              children: [
                                JsxRuntime.jsx("li", {
                                      children: "National Presidential Scholarship for Science (full-tuition scholarship)"
                                    }),
                                JsxRuntime.jsx("li", {
                                      children: "Intern@ROPAS (Jan 2022 – Feb 2024)"
                                    }),
                                JsxRuntime.jsx("li", {
                                      children: "Leave of absence for military duty during 2020 – 2021"
                                    }),
                                JsxRuntime.jsxs("li", {
                                      children: [
                                        JsxRuntime.jsx("span", {
                                              children: "cum laude; ",
                                              className: "italic"
                                            }),
                                        "GPA 3.81/4.3"
                                      ]
                                    })
                              ]
                            }),
                        JsxRuntime.jsx("li", {
                              children: "Korea Science Academy of KAIST (Mar 2015 – Feb 2018)"
                            }),
                        JsxRuntime.jsx("ul", {
                              children: JsxRuntime.jsx("li", {
                                    children: "GPA 4.05/4.3"
                                  })
                            })
                      ]
                    }),
                JsxRuntime.jsx("h2", {
                      children: "Teaching"
                    }),
                JsxRuntime.jsxs("ul", {
                      children: [
                        JsxRuntime.jsx("li", {
                              children: "2022 Spring: Programming Language (TA)"
                            }),
                        JsxRuntime.jsx("li", {
                              children: "2024 Spring: Programming Language (TA)"
                            })
                      ]
                    }),
                JsxRuntime.jsx("h2", {
                      children: "Contact Information"
                    }),
                JsxRuntime.jsx("a", {
                      children: JsxRuntime.jsx("address", {
                            children: "jhlee (at) ropas[.snu.ac.kr]"
                          }),
                      href: "https://mailhide.io/e/P9QWrvgX",
                      target: "_blank"
                    }),
                JsxRuntime.jsxs("address", {
                      children: [
                        "Room 312-2, Bldg 302",
                        JsxRuntime.jsx("br", {}),
                        JsxRuntime.jsx("a", {
                              children: "Dept. of Computer Science and Engineering",
                              href: "http://cse.snu.ac.kr/",
                              target: "_blank"
                            }),
                        JsxRuntime.jsx("br", {}),
                        "Seoul National University"
                      ]
                    })
              ],
              className: "px-6 py-12 max-w-xl mx-auto md:max-w-4xl prose text-lg"
            });
}

var make = Home;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
