// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Home(props) {
  return JsxRuntime.jsxs("article", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Jay Lee"
                    }),
                JsxRuntime.jsxs("ul", {
                      children: [
                        JsxRuntime.jsx("li", {
                              children: JsxRuntime.jsx("a", {
                                    children: "GitHub profile",
                                    href: "https://github.com/Zeta611"
                                  })
                            }),
                        JsxRuntime.jsx("li", {
                              children: JsxRuntime.jsx("a", {
                                    children: "Curriculum Vitae",
                                    href: "https://nbviewer.org/github/Zeta611/curriculum-vitae/blob/main/resume.pdf"
                                  })
                            }),
                        JsxRuntime.jsx("li", {
                              children: JsxRuntime.jsx("a", {
                                    children: "Personal blog",
                                    href: "https://jaylee.xyz"
                                  })
                            })
                      ]
                    }),
                JsxRuntime.jsx("img", {
                      className: "w-[270px] h-[360px]",
                      alt: "Photo of Jay Lee",
                      src: "./jhlee_photo.jpg"
                    }),
                JsxRuntime.jsx("h2", {
                      children: "Research Interests"
                    }),
                JsxRuntime.jsxs("ul", {
                      children: [
                        JsxRuntime.jsx("li", {
                              children: "Programming Languages"
                            }),
                        JsxRuntime.jsx("li", {
                              children: "Program Analysis"
                            }),
                        JsxRuntime.jsx("li", {
                              children: "Software Engineering"
                            }),
                        JsxRuntime.jsx("li", {
                              children: "Functional Programming"
                            })
                      ]
                    }),
                JsxRuntime.jsx("h2", {
                      children: "Research Projects"
                    }),
                JsxRuntime.jsxs("ul", {
                      children: [
                        JsxRuntime.jsxs("li", {
                              children: [
                                "Retargeting an Abstract Interpreter for a New Language by Partial Evaluation",
                                JsxRuntime.jsx("ul", {
                                      children: JsxRuntime.jsx("li", {
                                            children: "Ongoing research"
                                          })
                                    })
                              ]
                            }),
                        JsxRuntime.jsxs("li", {
                              children: [
                                JsxRuntime.jsx("a", {
                                      children: "React-tRace: A Semantics for Understanding React Hooks",
                                      href: "https://github.com/Zeta611/react-trace"
                                    }),
                                JsxRuntime.jsxs("ul", {
                                      children: [
                                        JsxRuntime.jsx("li", {
                                              children: "Submitted to OOPSLA '25"
                                            }),
                                        JsxRuntime.jsx("li", {
                                              children: JsxRuntime.jsx("a", {
                                                    children: "The React-tRace interpreter and visualizer",
                                                    href: "https://jaylee.xyz/react-trace"
                                                  })
                                            })
                                      ]
                                    })
                              ]
                            }),
                        JsxRuntime.jsxs("li", {
                              children: [
                                JsxRuntime.jsx("a", {
                                      children: "STAPPL: Statically Typed Probabilistic Programming Language",
                                      href: "https://github.com/Zeta611/stappl"
                                    }),
                                JsxRuntime.jsxs("ul", {
                                      children: [
                                        JsxRuntime.jsx("li", {
                                              children: "Final project for SNU graduate course Probabilistic Graphical Models (ranked top-3)"
                                            }),
                                        JsxRuntime.jsx("li", {
                                              children: JsxRuntime.jsx("a", {
                                                    children: "Technical Report",
                                                    href: "./stappl.pdf"
                                                  })
                                            })
                                      ]
                                    })
                              ]
                            }),
                        JsxRuntime.jsxs("li", {
                              children: [
                                JsxRuntime.jsx("a", {
                                      children: "Rust MIR Escape Analysis: An Application to Protecting Dynamic Pointer Metadata",
                                      href: "https://github.com/Zeta611/mir-escape-analysis"
                                    }),
                                JsxRuntime.jsx("ul", {
                                      children: JsxRuntime.jsx("li", {
                                            children: JsxRuntime.jsx("a", {
                                                  children: "SNU BS Thesis",
                                                  href: "./bs-thesis-rust-mir-escape-analysis.pdf"
                                                })
                                          })
                                    })
                              ]
                            }),
                        JsxRuntime.jsx("li", {
                              children: JsxRuntime.jsx("a", {
                                    children: "prospect-analyzer: a shape-checker for programs with holes",
                                    href: "https://github.com/Zeta611/prospect-analyzer"
                                  })
                            })
                      ]
                    }),
                JsxRuntime.jsx("h2", {
                      children: "Education"
                    }),
                JsxRuntime.jsxs("ul", {
                      children: [
                        JsxRuntime.jsx("li", {
                              children: "MS, Computer Science and Engineering, Seoul National University (Mar 2024 – )"
                            }),
                        JsxRuntime.jsxs("ul", {
                              children: [
                                JsxRuntime.jsx("li", {
                                      children: "ROPAS (Mar 2024 – )"
                                    }),
                                JsxRuntime.jsx("li", {
                                      children: "GPA 4.15/4.3"
                                    })
                              ]
                            }),
                        JsxRuntime.jsx("li", {
                              children: "BS, Electrical and Computer Engineering, Seoul National University (Mar 2018 – Feb 2024)"
                            }),
                        JsxRuntime.jsxs("ul", {
                              children: [
                                JsxRuntime.jsx("li", {
                                      children: "National Presidential Scholarship for Science (full-tuition scholarship)"
                                    }),
                                JsxRuntime.jsx("li", {
                                      children: "Undergraduate Internship at ROPAS (Jan 2022 – Feb 2024)"
                                    }),
                                JsxRuntime.jsx("li", {
                                      children: "Leave of absence for military duty during 2020 – 2021"
                                    }),
                                JsxRuntime.jsxs("li", {
                                      children: [
                                        JsxRuntime.jsx("span", {
                                              children: "cum laude; ",
                                              className: "italic"
                                            }),
                                        "GPA 3.81/4.3"
                                      ]
                                    })
                              ]
                            }),
                        JsxRuntime.jsx("li", {
                              children: "Korea Science Academy of KAIST (Mar 2015 – Feb 2018)"
                            }),
                        JsxRuntime.jsx("ul", {
                              children: JsxRuntime.jsx("li", {
                                    children: "GPA 4.05/4.3"
                                  })
                            })
                      ]
                    }),
                JsxRuntime.jsx("h2", {
                      children: "Teaching"
                    }),
                JsxRuntime.jsxs("ul", {
                      children: [
                        JsxRuntime.jsx("li", {
                              children: "2022 Spring: Programming Languages (TA)"
                            }),
                        JsxRuntime.jsx("li", {
                              children: "2024 Spring: Programming Languages (TA)"
                            }),
                        JsxRuntime.jsx("ul", {
                              children: JsxRuntime.jsx("li", {
                                    children: "Received the best TA award"
                                  })
                            }),
                        JsxRuntime.jsx("li", {
                              children: "2025 Spring: Programming Languages (TA)"
                            }),
                        JsxRuntime.jsx("li", {
                              children: "2025 Spring: Program Analysis (TA)"
                            })
                      ]
                    }),
                JsxRuntime.jsx("h2", {
                      children: "Miscellaneous"
                    }),
                JsxRuntime.jsxs("ul", {
                      children: [
                        JsxRuntime.jsx("li", {
                              children: JsxRuntime.jsx("a", {
                                    children: "easyword.kr: A platform for translating CS jargons into easy to understand Korean",
                                    href: "https://easyword.kr"
                                  })
                            }),
                        JsxRuntime.jsx("li", {
                              children: JsxRuntime.jsx("a", {
                                    children: "simplebnf: an intuitive BNF grammar typesetting in LaTeX using DSL",
                                    href: "https://github.com/Zeta611/simplebnf"
                                  })
                            }),
                        JsxRuntime.jsx("li", {
                              children: JsxRuntime.jsx("a", {
                                    children: "Intel International Science and Engineering Fair 2017 (ISEF 2017) Finalist",
                                    href: "https://sspcdn.blob.core.windows.net/files/Documents/SEP/ISEF/2017/Attendees/Programs/Book.pdf"
                                  })
                            })
                      ]
                    }),
                JsxRuntime.jsx("h2", {
                      children: "Contact Information"
                    }),
                JsxRuntime.jsx("a", {
                      children: JsxRuntime.jsx("address", {
                            children: "jhlee (at) ropas[.snu.ac.kr]"
                          }),
                      href: "https://mailhide.io/e/P9QWrvgX",
                      target: "_blank"
                    }),
                JsxRuntime.jsxs("address", {
                      children: [
                        "Room 312-2, Bldg 302",
                        JsxRuntime.jsx("br", {}),
                        JsxRuntime.jsx("a", {
                              children: "Dept. of Computer Science and Engineering",
                              href: "http://cse.snu.ac.kr/",
                              target: "_blank"
                            }),
                        JsxRuntime.jsx("br", {}),
                        "Seoul National University"
                      ]
                    })
              ],
              className: "px-6 py-12 max-w-xl mx-auto md:max-w-4xl prose text-lg"
            });
}

var make = Home;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
